= Ядро обработки данных
ifdef::env-antora[]
include::common:ROOT:partial$attr-common.adoc[]
endif::[]

ifndef::env-antora[]
include::../../../../common/modules/ROOT/partials/attr-common.adoc[]
endif::[]
// :plantuml-server-url: https://www.plantuml.com/plantuml

== Назначение компонента

Компонент предназначен для выполнения ключевых функций в рамках программной системы.

== Структура

Компонент предназначен для выполнения ключевых функций в рамках программной системы.

* Комплекс технических средств
* Руководство пользователя
* Описание программы
* Руководство системного программиста

== Архитектурная схема компонента

Компонент предназначен для выполнения ключевых функций в рамках программной системы.

* Комплекс технических средств
* Руководство пользователя
* Описание программы
* Руководство системного программиста

== Схема взаимодействия подсистем
Компонент предназначен для выполнения ключевых функций в рамках программной системы.

* Комплекс технических средств
* Руководство пользователя
* Описание программы
* Руководство системного программиста

.Схема архитектуры компонента


.Схема взаимодействия компонентов всей системы


== Схема взаимодействия подсистем

.Схема архитектуры компонента


.Схема взаимодействия компонентов всей системы


== Архитектурная схема компонента



== Схема взаимодействия компонентов всей системы


== Схема взаимодействия подсистем

.Схема архитектуры компонента

[plantuml, format=svg]
----
@startuml
actor User
rectangle Component {
  User --> Interface
  Interface --> Logic
  Logic --> Database
}
@enduml
----


== Архитектурная схема компонента


.Схема взаимодействия компонентов всей системы
[plantuml, format=svg]
----
@startuml
title Схема взаимодействия компонентов системы

package "Внешние системы" {
  [Сторонняя ИС] as ExternalSystem
}

package "Взаимодействие" {
  [Интеграционный модуль] as Integration
}

package "Обработка данных" {
  [Ядро обработки] as Engine
}

package "Отчётность" {
  [Модуль отчётов] as Reports
}

package "Безопасность" {
  [Подсистема безопасности] as Security
}

ExternalSystem --> Integration : API / файлы
Integration --> Engine : события
Engine --> Reports : агрегированные данные
Engine --> Security : проверка доступа
@enduml

----