= Комплекс технических средств
ifdef::env-antora[]
include::common:ROOT:partial$attr-common.adoc[]
endif::[]

ifndef::env-antora[]
include::../../../../common/modules/ROOT/partials/attr-common.adoc[]
endif::[]

== Назначение документа

Документ входит в состав компонента "Ядро обработки данных" и описывает модуль "Комплекс технических средств".

== Структура и содержание

. Назначение
.. Задачи
. Функции
.. Модули
. Примеры использования
.. Первый
.. Второй

== Назначение компонента

Компонент предназначен для выполнения ключевых функций в рамках программной системы.


== Структура

Компонент предназначен для выполнения ключевых функций в рамках программной системы.
Компонент предназначен для выполнения ключевых функций в рамках программной системы.
Компонент предназначен для выполнения ключевых функций в рамках программной системы.

Компонент предназначен для выполнения ключевых функций в рамках программной системы.
Компонент предназначен для выполнения ключевых функций в рамках программной системы.
// * Комплекс технических средств
Компонент предназначен для выполнения ключевых функций в рамках программной системы.
Компонент предназначен для выполнения ключевых функций в рамках программной системы.
Компонент предназначен для выполнения ключевых функций в рамках программной системы.
// * Комплекс технических средств
Компонент предназначен для выполнения ключевых функций в рамках программной системы.
Компонент предназначен для выполнени Компонент предназначен для выполненидля выполнени

// * Описание программы
// * Руководство системного программиста

// :num_t: {counter:table-number}

// dsgfdfgsdf <<id_t_{num_t}, Table {num_t}>>

// [#id_t_{num_t}]
// .TAb bdfgsdfgsdfgsdf
// [cols="1,2", options="header, breakable"]
// |===
// |dfgdf|dfgdf
// |dfgdfg|dfgdf
// |ghjkgh|dfgdfgd
// |dfgdfg|dfgdf
// |ghjkgh|dfgdfgd
// |dfgdfg|dfgdf
// |ghjkgh|dfgdfgd
// |===

=== Архитектурная схема компонента
Компонент предназначен для выполнения ключевых функций в рамках программной системы.
Компонент предназначен для выполнения ключевых функций в рамках программной системы.
Компонент предназначен для выполнения ключевых функций в рамках программной системы.
Компонент предназначен для выполнения ключевых функций в рамках программной системы.
Компонент предназначен для выполнения ключевых функций в рамках программной системы.
Компонент предназначен для выполнения ключевых функций в рамках программной системы.
Компонент предназначен для выполнения ключевых функций в рамках программной системы.

* Комплекс технических средств
* Руководство пользователя
* Описание программы

== Схема взаимодействия подсистем

Компонент предназначен для выполнения ключевых функций в рамках программной системы.

* Комплекс технических средств
* Руководство пользователя
* Описание программы
* Руководство системного программиста

.Схема архитектуры компонента
